openapi: 3.0.2
info:
  title: ''
  version: ''
paths:
  /ordersystem/products/{var}:
    get:
      operationId: retrieveProduct
      description: ''
      parameters:
      - name: var
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - ordersystem
    post:
      operationId: createProduct
      description: ''
      parameters:
      - name: var
        in: path
        required: true
        description: ''
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema: {}
          application/x-www-form-urlencoded:
            schema: {}
          multipart/form-data:
            schema: {}
      responses:
        '201':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - ordersystem
    put:
      operationId: updateProduct
      description: ''
      parameters:
      - name: var
        in: path
        required: true
        description: ''
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema: {}
          application/x-www-form-urlencoded:
            schema: {}
          multipart/form-data:
            schema: {}
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - ordersystem
    delete:
      operationId: destroyProduct
      description: ''
      parameters:
      - name: var
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '204':
          description: ''
      tags:
      - ordersystem
  /ordersystem/orders/{var}:
    get:
      operationId: retrieveOrder
      description: ''
      parameters:
      - name: var
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - ordersystem
    post:
      operationId: createOrder
      description: ''
      parameters:
      - name: var
        in: path
        required: true
        description: ''
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema: {}
          application/x-www-form-urlencoded:
            schema: {}
          multipart/form-data:
            schema: {}
      responses:
        '201':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - ordersystem
    put:
      operationId: updateOrder
      description: ''
      parameters:
      - name: var
        in: path
        required: true
        description: ''
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema: {}
          application/x-www-form-urlencoded:
            schema: {}
          multipart/form-data:
            schema: {}
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - ordersystem
    delete:
      operationId: destroyOrder
      description: ''
      parameters:
      - name: var
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '204':
          description: ''
      tags:
      - ordersystem