# Generated by Django 4.1.3 on 2022-11-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ordersystem_api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.IntegerField()),
                ("name", models.CharField(max_length=50)),
                ("visiblity", models.BooleanField(default=True)),
            ],
        ),
    ]
