# Generated by Django 4.1.5 on 2023-03-04 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersystem_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_donation',
        ),
        migrations.AddField(
            model_name='order',
            name='puh',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
