# Generated by Django 4.1.5 on 2023-01-30 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ordersystem_api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="custo_id",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
