# Generated by Django 4.1.7 on 2023-03-08 16:43

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.JSONField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("ready", models.BooleanField(blank=True, default=False)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("customer", models.CharField(max_length=50)),
            ],
        ),
    ]
